print("Hola Mundo te digo 'Hola'")
print(100+50)
print('100+50')
print("Hola"+'Fede')
print("Hola "+'Fede')
print("Hola"+' Fede')
print("Hola"+'Fede')
print("Hola" + " " + 'Fede')
print("Me llamo \"Federico\"")
print("Esta es una linea\nY esta es otra linea")
print("\tEsta es la tercera linea")
print("This isn\'t a number")
print("Este texto \\ es una barra invertida")
input("Dime tu nombre:")
input("Dime tu apellido:")
print("Tu nombre es " + input("Dime tu nombre: ") + " " + input("Dime tu apellido: "))
